# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Journal
email: mvellandi@hotmail.com
description: For document meta info
baseurl: "/journal" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: servusmario
github_username:  mvellandi

# Build settings
markdown: kramdown
permalink: /:title/ # optionally, we can build the style ourself, e.g. /:title/
keep_files:
  - wp-content
permalink: /:title/ # optionally, we can build the style ourself, e.g. /:title

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: Mario Vellandi
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
